# helm/clahan-academy/templates/secretproviders/ai-secretprovider.yaml

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: clahan-ai-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.azure.workloadIdentity.ai.clientId }}
    keyvaultName: {{ .Values.global.azure.keyVaultName }}
    cloudName: ""
    tenantID: {{ .Values.global.azure.tenantId }}
    objects: |
      array:
        - |
          objectName: ai-port
          objectType: secret
        - |
          objectName: ollama-url
          objectType: secret
  secretObjects:
    - secretName: clahan-ai-secrets
      type: Opaque
      data:
        - key: PORT
          objectName: ai-port
        - key: OLLAMA_URL
          objectName: ollama-url
