# kubernetes/frontend-service/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: production
  annotations:
    azure.workload.identity/client-id: "PLACEHOLDER_FRONTEND_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false
