# helm/clahan-academy/templates/services/ai-svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: clahan-academy
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ai.port }}
      targetPort: {{ .Values.ai.port }}
      protocol: TCP
      name: http
  selector:
    app: ai-service
