# helm/clahan-academy/templates/deployments/judge0-redis-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: judge0-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-redis
  template:
    metadata:
      labels:
        app: judge0-redis
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          command: ["redis-server", "--save", "", "--appendonly", "no"]
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
