# helm/clahan-academy/templates/serviceaccounts/notification-sa.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: clahan-notification-sa
  namespace: clahan-academy
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.notification.clientId | quote }}
  labels:
    azure.workload.identity/use: "true"
