# kubernetes/judge0/redis-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-redis
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-redis
  template:
    metadata:
      labels:
        app: judge0-redis
    spec:
      nodeSelector:
        pool: ai
      tolerations:
        - key: dedicated
          operator: Equal
          value: ai
          effect: NoSchedule
      containers:
        - name: judge0-redis
          image: redis:7-alpine
          command: ["redis-server", "--save", "", "--appendonly", "no"]
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
