# helm/clahan-academy/templates/secretproviders/proctoring-secretprovider.yaml

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: clahan-proctoring-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.azure.workloadIdentity.proctoring.clientId }}
    keyvaultName: {{ .Values.global.azure.keyVaultName }}
    cloudName: ""
    tenantID: {{ .Values.global.azure.tenantId }}
    objects: |
      array:
        - |
          objectName: proctoring-port
          objectAlias: PORT
          objectType: secret
        - |
          objectName: db-connection-string
          objectAlias: DATABASE_URL
          objectType: secret
        - |
          objectName: redis-connection-string
          objectAlias: REDIS_URL
          objectType: secret
        - |
          objectName: jwt-access-secret
          objectAlias: JWT_ACCESS_SECRET
          objectType: secret
        - |
          objectName: ai-service-url
          objectAlias: AI_SERVICE_URL
          objectType: secret
        - |
          objectName: tab-switch-limit
          objectAlias: TAB_SWITCH_LIMIT
          objectType: secret
        - |
          objectName: mobile-phone-limit
          objectAlias: MOBILE_PHONE_LIMIT
          objectType: secret
        - |
          objectName: book-limit
          objectAlias: BOOK_LIMIT
          objectType: secret
        - |
          objectName: multiple-faces-limit
          objectAlias: MULTIPLE_FACES_LIMIT
          objectType: secret
        - |
          objectName: no-face-timeout-ms
          objectAlias: NO_FACE_TIMEOUT_MS
          objectType: secret
        - |
          objectName: fullscreen-exit-limit
          objectAlias: FULLSCREEN_EXIT_LIMIT
          objectType: secret
