# helm/clahan-academy/templates/services/admin-svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: admin-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    app: admin-service
