# helm/clahan-academy/templates/secretproviders/admin-secretprovider.yaml

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: clahan-admin-secrets
  namespace: clahan-academy
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.azure.workloadIdentity.admin.clientId }}
    keyvaultName: {{ .Values.global.azure.keyVaultName }}
    cloudName: ""
    tenantID: {{ .Values.global.azure.tenantId }}
    objects: |
      array:
        - |
          objectName: admin-port
          objectType: secret
        - |
          objectName: db-connection-string
          objectType: secret
        - |
          objectName: redis-connection-string
          objectType: secret
        - |
          objectName: jwt-access-secret
          objectType: secret
        - |
          objectName: rate-limit-max
          objectType: secret
  secretObjects:
    - secretName: clahan-admin-secrets
      type: Opaque
      data:
        - key: PORT
          objectName: admin-port
        - key: DATABASE_URL
          objectName: db-connection-string
        - key: REDIS_URL
          objectName: redis-connection-string
        - key: JWT_ACCESS_SECRET
          objectName: jwt-access-secret
        - key: RATE_LIMIT_MAX
          objectName: rate-limit-max
