# helm/clahan-academy/templates/storage/ollama-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes: [ReadWriteMany]
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
