# kubernetes/proctoring-service/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: proctoring-sa
  namespace: production
  annotations:
    azure.workload.identity/client-id: "PLACEHOLDER_PROCTORING_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false
