# kubernetes/student-service/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-sa
  namespace: production
  annotations:
    azure.workload.identity/client-id: "PLACEHOLDER_STUDENT_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false
