# helm/clahan-academy/templates/secretproviders/notification-secretprovider.yaml

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: clahan-notification-secrets
  namespace: clahan-academy
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.azure.workloadIdentity.notification.clientId }}
    keyvaultName: {{ .Values.azure.keyVaultName }}
    cloudName: ""
    tenantID: {{ .Values.azure.tenantId }}
    objects: |
      array:
        - |
          objectName: notification-port
          objectType: secret
        - |
          objectName: redis-connection-string
          objectType: secret
        - |
          objectName: smtp-host
          objectType: secret
        - |
          objectName: smtp-port
          objectType: secret
        - |
          objectName: smtp-user
          objectType: secret
        - |
          objectName: smtp-pass
          objectType: secret
        - |
          objectName: smtp-from
          objectType: secret
        - |
          objectName: frontend-url
          objectType: secret
        - |
          objectName: sendgrid-api-key
          objectType: secret
        - |
          objectName: sendgrid-from
          objectType: secret
  secretObjects:
    - secretName: clahan-notification-secrets
      type: Opaque
      data:
        - key: PORT
          objectName: notification-port
        - key: REDIS_URL
          objectName: redis-connection-string
        - key: SMTP_HOST
          objectName: smtp-host
        - key: SMTP_PORT
          objectName: smtp-port
        - key: SMTP_USER
          objectName: smtp-user
        - key: SMTP_PASS
          objectName: smtp-pass
        - key: SMTP_FROM
          objectName: smtp-from
        - key: FRONTEND_URL
          objectName: frontend-url
        - key: SENDGRID_API_KEY
          objectName: sendgrid-api-key
        - key: SENDGRID_FROM
          objectName: sendgrid-from
