# helm/clahan-academy/templates/secretproviders/proctoring-secretprovider.yaml

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: clahan-proctoring-secrets
  namespace: clahan-academy
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.azure.workloadIdentity.proctoring.clientId }}
    keyvaultName: {{ .Values.azure.keyVaultName }}
    cloudName: ""
    tenantID: {{ .Values.azure.tenantId }}
    objects: |
      array:
        - |
          objectName: proctoring-port
          objectType: secret
        - |
          objectName: db-connection-string
          objectType: secret
        - |
          objectName: redis-connection-string
          objectType: secret
        - |
          objectName: jwt-access-secret
          objectType: secret
        - |
          objectName: ai-service-url
          objectType: secret
        - |
          objectName: tab-switch-limit
          objectType: secret
        - |
          objectName: mobile-phone-limit
          objectType: secret
        - |
          objectName: book-limit
          objectType: secret
        - |
          objectName: multiple-faces-limit
          objectType: secret
        - |
          objectName: no-face-timeout-ms
          objectType: secret
        - |
          objectName: fullscreen-exit-limit
          objectType: secret
  secretObjects:
    - secretName: clahan-proctoring-secrets
      type: Opaque
      data:
        - key: PORT
          objectName: proctoring-port
        - key: DATABASE_URL
          objectName: db-connection-string
        - key: REDIS_URL
          objectName: redis-connection-string
        - key: JWT_ACCESS_SECRET
          objectName: jwt-access-secret
        - key: AI_SERVICE_URL
          objectName: ai-service-url
        - key: TAB_SWITCH_LIMIT
          objectName: tab-switch-limit
        - key: MOBILE_PHONE_LIMIT
          objectName: mobile-phone-limit
        - key: BOOK_LIMIT
          objectName: book-limit
        - key: MULTIPLE_FACES_LIMIT
          objectName: multiple-faces-limit
        - key: NO_FACE_TIMEOUT_MS
          objectName: no-face-timeout-ms
        - key: FULLSCREEN_EXIT_LIMIT
          objectName: fullscreen-exit-limit
