# kubernetes/auth-service/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: production
  annotations:
    azure.workload.identity/client-id: "PLACEHOLDER_AUTH_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false
