# kubernetes/ai-service/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-sa
  namespace: production
  annotations:
    azure.workload.identity/client-id: "PLACEHOLDER_AI_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false
