# helm/clahan-academy/templates/serviceaccounts/exam-sa.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: clahan-exam-sa
  namespace: clahan-academy
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.azure.workloadIdentity.exam.clientId | quote }}
  labels:
    azure.workload.identity/use: "true"
