# kubernetes/exam-service/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: exam-sa
  namespace: production
  annotations:
    azure.workload.identity/client-id: "PLACEHOLDER_EXAM_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false
