# helm/clahan-academy/values-dev.yaml

# Dev environment overrides
# Applied on top of values.yaml for dev deployments
# ArgoCD uses: values.yaml + values-dev.yaml

global:
  environment: dev
  namespace: clahan-dev

ingress:
  host: dev.clahaanacademy.online

# Dev Registry Overrides
frontend:
  replicaCount: 1
  image:
    repository: acrclahan65bf2554dev.azurecr.io/clahan-frontend

auth:
  replicaCount: 1
  autoscaling:
    enabled: false
  image:
    repository: acrclahan65bf2554dev.azurecr.io/clahan-auth

admin:
  replicaCount: 1
  image:
    repository: acrclahan65bf2554dev.azurecr.io/clahan-admin

student:
  replicaCount: 1
  image:
    repository: acrclahan65bf2554dev.azurecr.io/clahan-student

exam:
  replicaCount: 1
  autoscaling:
    enabled: false
  image:
    repository: acrclahan65bf2554dev.azurecr.io/clahan-exam

proctoring:
  replicaCount: 1
  autoscaling:
    enabled: false
  image:
    repository: acrclahan65bf2554dev.azurecr.io/clahan-proctoring

notification:
  replicaCount: 1
  image:
    repository: acrclahan65bf2554dev.azurecr.io/clahan-notification

ai:
  replicaCount: 1
  image:
    repository: acrclahan65bf2554dev.azurecr.io/clahan-ai
