# helm/clahan-academy/values-prod.yaml

# Production environment overrides
# Applied on top of values.yaml for dev deployments
# ArgoCD uses: values.yaml + values-prod.yaml

global:
  environment: prod
  namespace: clahan-production
  azure:
    keyVaultName: "kv-clahan-prod"
    workloadIdentity:
      frontend:
        clientId: "21a03db3-0c2a-43f3-bc83-52c532321ea3"
      auth:
        clientId: "b14430f8-73b7-4ad0-835d-007023b71829"
      admin:
        clientId: "741a5cfb-560d-4e26-89f0-d718ec4a5c29"
      student:
        clientId: "634cbea3-9f93-4aad-ae9b-547c59643b9e"
      exam:
        clientId: "5cd542c7-ea5b-4721-a4b3-d91f42a69496"
      proctoring:
        clientId: "66ff5262-df9e-45b7-a2e8-b5a7b8da8e50"
      notification:
        clientId: "ab4386e7-47ed-40f8-a8ca-9a03afa20678"
      ai:
        clientId: "eb4b6554-8710-4bee-b8fb-5a4350c0bacb"
ingress:
  host: clahaanacademy.online
# Prod: scaled down to 1 replica to save resources (frontend and auth set to 2 for capstone evaluation compliance)
frontend:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  image:
    tag: v0.5.4
auth:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
  image:
    tag: v0.5.4
admin:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 65
  image:
    tag: v0.5.4
student:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 65
  image:
    tag: v0.5.4
exam:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 60
  image:
    tag: v0.5.4
proctoring:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 60
  image:
    tag: v0.5.4
notification:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 65
  image:
    tag: v0.5.4
ai:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 65
  image:
    tag: v0.5.4
