# helm/clahan-academy/values.yaml

global:
  imageRegistry: acrclahan65bf2554.azurecr.io
  namespace: clahan-academy
  environment: dev
  imagePullPolicy: Always
  azure:
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    keyVaultName: "kv-clahan-65bf2554"
    workloadIdentity:
      frontend:
        clientId: "b00bdac0-b4d2-41f0-a4b2-96bbc8df4ff7"
      auth:
        clientId: "4057a136-4ae8-4f77-806e-c615329f45c4"
      admin:
        clientId: "2ed2021a-cdec-411a-be5a-949a2e14f193"
      student:
        clientId: "473f9fb6-2b86-40d8-82cc-56fbfcedb1d1"
      exam:
        clientId: "13f23a5c-8f0d-4ebc-a63a-877f9a7cf451"
      proctoring:
        clientId: "0cd010f7-269e-4b62-a429-079f2768bee0"
      notification:
        clientId: "947e184d-abd5-4c02-b319-015ab8336a46"
      ai:
        clientId: "7a4fd5b2-7189-4155-b8b2-f0baa2759d88"
  
frontend:
  image:
    repository: acrclahan65bf2554.azurecr.io/clahan-frontend
    tag: "latest"
  replicaCount: 2
  port: 5173
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

auth:
  image:
    repository: acrclahan65bf2554.azurecr.io/clahan-auth
    tag: "latest"
  replicaCount: 2
  port: 4001
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

admin:
  image:
    repository: acrclahan65bf2554.azurecr.io/clahan-admin
    tag: "latest"
  replicaCount: 1
  port: 4002
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75

student:
  image:
    repository: acrclahan65bf2554.azurecr.io/clahan-student
    tag: "latest"
  replicaCount: 1
  port: 4003
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75

exam:
  image:
    repository: acrclahan65bf2554.azurecr.io/clahan-exam
    tag: "latest"
  replicaCount: 2
  port: 4004
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

proctoring:
  image:
    repository: acrclahan65bf2554.azurecr.io/clahan-proctoring
    tag: "latest"
  replicaCount: 2
  port: 4005
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

notification:
  image:
    repository: acrclahan65bf2554.azurecr.io/clahan-notification
    tag: "latest"
  replicaCount: 1
  port: 4006
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75

ai:
  image:
    repository: acrclahan65bf2554.azurecr.io/clahan-ai
    tag: "latest"
  replicaCount: 1
  port: 8000
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1500m"
      memory: "2Gi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75
  nodeSelector:
    pool: ai
  tolerations:
    - key: dedicated
      operator: Equal
      value: ai
      effect: NoSchedule

ollama:
  image: ollama/ollama:latest
  replicaCount: 1
  port: 11434
  model: phi3
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1500m"
      memory: "3Gi"
  nodeSelector:
    pool: ai
  tolerations:
    - key: dedicated
      operator: Equal
      value: ai
      effect: NoSchedule
  persistence:
    size: 20Gi
    storageClass: azurefile-csi

judge0:
  api:
    image: mrkushalsm/judge0:cgv2
    port: 2358
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
  worker:
    image: mrkushalsm/judge0:cgv2
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "2000m"
        memory: "2Gi"
  redis:
    image: redis:7-alpine
    port: 6379
  nodeSelector:
    pool: ai
  tolerations:
    - key: dedicated
      operator: Equal
      value: ai
      effect: NoSchedule

ingress:
  enabled: true
  host: clahaanacademy.online
  tls:
    enabled: true
    secretName: clahan-tls-secret

gateway:
  className: kgateway
