# argocd/prod/application.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clahan-academy-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: clahan-academy
    environment: prod
spec:
  project: clahan-academy-prod
  
  source:
    repoURL: https://github.com/clahan-academy/clahan-academy-helm.git
    targetRevision: main
    path: clahan-academy
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: clahan-production
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3
  

