# kubernetes/admin-service/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-sa
  namespace: production
  annotations:
    azure.workload.identity/client-id: "PLACEHOLDER_ADMIN_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false
