# kubernetes/notification-service/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-sa
  namespace: production
  annotations:
    azure.workload.identity/client-id: "PLACEHOLDER_NOTIFICATION_CLIENT_ID"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false
