# helm/clahan-academy/templates/secretproviders/notification-secretprovider.yaml

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: clahan-notification-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.azure.workloadIdentity.notification.clientId }}
    keyvaultName: {{ .Values.global.azure.keyVaultName }}
    cloudName: ""
    tenantID: {{ .Values.global.azure.tenantId }}
    objects: |
      array:
        - |
          objectName: notification-port
          objectAlias: PORT
          objectType: secret
        - |
          objectName: redis-connection-string
          objectAlias: REDIS_URL
          objectType: secret
        - |
          objectName: smtp-host
          objectAlias: SMTP_HOST
          objectType: secret
        - |
          objectName: smtp-port
          objectAlias: SMTP_PORT
          objectType: secret
        - |
          objectName: smtp-user
          objectAlias: SMTP_USER
          objectType: secret
        - |
          objectName: smtp-pass
          objectAlias: SMTP_PASS
          objectType: secret
        - |
          objectName: smtp-from
          objectAlias: SMTP_FROM
          objectType: secret
        - |
          objectName: frontend-url
          objectAlias: FRONTEND_URL
          objectType: secret
        - |
          objectName: sendgrid-api-key
          objectAlias: SENDGRID_API_KEY
          objectType: secret
        - |
          objectName: sendgrid-from
          objectAlias: SENDGRID_FROM
          objectType: secret
